name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build plugins
        run: |
          chmod +x gradlew
          ./gradlew make generateUpdaterJson -Dorg.gradle.jvmargs="-Xmx12g -XX:+UseParallelGC" -Dorg.gradle.vfs.watch=false

      - name: Deploy plugins to builds
        run: |
          install -D -t builds plugins/*/build/outputs/*.zip build/outputs/updater.json
          cd builds

          git init
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          git remote add origin "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}"
          git fetch --depth 1 --filter=blob:none origin builds || false && git reset FETCH_HEAD

          git add -- .
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push origin HEAD:builds